=== skarx88/Testing/HarnessAnalyzer/Solution/Documentation/Feature Wishes Daimler for Release 2020/ValidityCheckContainer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="ValidityCheckContainer">
		<xs:annotation>
			<xs:documentation>Gültigkeitsprüfungs-Container</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Creator" type="xs:string">
					<xs:annotation>
						<xs:documentation>Ersteller</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="DateOfCreation" type="xs:dateTime">
					<xs:annotation>
						<xs:documentation>Datum der Erstellung</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Project" type="xs:string">
					<xs:annotation>
						<xs:documentation>Baureihe</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="PartNumber" type="xs:string" nillable="false">
					<xs:annotation>
						<xs:documentation>Teilenummer des Leitungssatzes</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Version" type="xs:string" nillable="false">
					<xs:annotation>
						<xs:documentation>Version (Datum) des Leitungssatzes</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="ValidityCheckEntry"/>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ValidityCheckEntry">
		<xs:annotation>
			<xs:documentation>Gültigkeitsprüfungs-Eintrag</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Code" type="xs:string">
					<xs:annotation>
						<xs:documentation>GP-Code</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Description" type="xs:string">
					<xs:annotation>
						<xs:documentation>GP-Beschreibung</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Text" type="xs:string">
					<xs:annotation>
						<xs:documentation>GP-Fehlertext</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ResolutionHint" type="xs:string">
					<xs:annotation>
						<xs:documentation>Lösung</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Type" type="xs:string">
					<xs:annotation>
						<xs:documentation>Meldungsart</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ID" type="xs:string">
				<xs:annotation>
					<xs:documentation>KBL-ID oder KBL-Sachnummer; Cavity_occurrence-Typ: Kombination aus Stecker-ID und Kammernummer getrennt durch ','</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="ObjectType" type="ObjectTypes">
				<xs:annotation>
					<xs:documentation>Accessory_occurrence; Assembly_part_occurrence; Cavity_occurrence; Cavity_seal_occurrence; Cavity_plug_occurrence; Co_pack_occurrence; Component_box_occurrence; Component_occurrence; Connector_occurrence; Core_occurrence; Dimension_specification; Fixing_occurrence; Fuse_occurrence; Node; Part; Segment; Special_terminal_occurrence; Special_wire_occurrence; Terminal_occurrence; Wire_occurrence; Wire_protection_occurrence; Wiring_group</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="ObjectTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Accessory_occurrence"/>
			<xs:enumeration value="Assembly_part_occurrence"/>
			<xs:enumeration value="Cavity_occurrence"/>
			<xs:enumeration value="Cavity_seal_occurrence"/>
			<xs:enumeration value="Cavity_plug_occurrence"/>
			<xs:enumeration value="Co_pack_occurrence"/>
			<xs:enumeration value="Component_box_occurrence"/>
			<xs:enumeration value="Component_occurrence"/>
			<xs:enumeration value="Connector_occurrence"/>
			<xs:enumeration value="Core_occurrence"/>
			<xs:enumeration value="Dimension_specification"/>
			<xs:enumeration value="Fixing_occurrence"/>
			<xs:enumeration value="Fuse_occurrence"/>
			<xs:enumeration value="Node"/>
			<xs:enumeration value="Part"/>
			<xs:enumeration value="Segment"/>
			<xs:enumeration value="Special_terminal_occurrence"/>
			<xs:enumeration value="Special_wire_occurrence"/>
			<xs:enumeration value="Terminal_occurrence"/>
			<xs:enumeration value="Wire_occurrence"/>
			<xs:enumeration value="Wire_protection_occurrence"/>
			<xs:enumeration value="Wiring_group"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== skarx88/Testing/HarnessAnalyzer/Solution/Documentation/Feature Wishes Daimler for Release 2020/ValidityCheckForA1775403906.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) von Florian Rappel (Zuken E3 GmbH) bearbeitet -->
<ValidityCheckContainer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Solutions/E3.HarnessAnalyzer/Documentation/Feature%20Wishes%20Daimler%20for%20Release%202020/ValidityCheckContainer.xsd">
	<Creator>Rappel</Creator>
	<DateOfCreation>2020-04-24T09:30:00Z</DateOfCreation>
	<Project>TestProject</Project>
	<PartNumber>A1775403906</PartNumber>
	<Version>2020-01-17</Version>
	<ValidityCheckEntry ID="FX.IR.5402" ObjectType="Accessory_occurrence">
		<Code>GP3007</Code>
		<Description>POS-Nr. mit erlaubtem Muster</Description>
		<Text>Die POS-Nr. 'P6332' hat kein gültiges Präfix.</Text>
		<ResolutionHint>Ein Teil in diesem LS Modul hat kein gültiges Präfix für PKW.
--> POS-Nummer überprüfen / Richtige POS-Nummer beantragen und KBL korrigieren.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="FX.IR.5402" ObjectType="Accessory_occurrence">
		<Code>GP3009</Code>
		<Description>Teile ohne Dummy-POS-Nr.</Description>
		<Text>Das Teil mit der Dummy POS-Nr. Z000 benötigt eine echte POS-Nr.</Text>
		<ResolutionHint>Ein Teil in diesem LS Modul hat noch keine echte POS-Nummer.
--> Richtige POS-Nummer beantragen und KBL korrigieren.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A103*1-B,1" ObjectType="Cavity_occurrence">
		<Code>GP4202</Code>
		<Description>Prüfung der verschlossenen Kammern eines Kontaktgehäuses</Description>
		<Text>Die Kammer 1 des Kontaktgehäuses A103*1-B sind in der KBL als verschlossen dokumentiert, in ConnectPARTS hingegen nicht.</Text>
		<ResolutionHint>Die verschlossenen Kammern des Kontaktgehäuses in der KBL (bestückt mit Blindstopfen-Sachnummer = 'VERSCHLOSSEN') gegen ConnectPARTS abgleichen, und die entsprechende KBL bzw. den Datensatz in ConnectPARTS anpassen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A103*1-B,1" ObjectType="Cavity_occurrence">
		<Code>GP4015</Code>
		<Description>Doppelbelegung Kammer melden</Description>
		<Text>Die Kammer 1 am Stecker A103*1-B ist mit mehr als einem Kontakt belegt</Text>
		<ResolutionHint>Beide Verbindungen des Doppelanschlags müssen vom selben Kontakt bzw. Ela referenziert werden</ResolutionHint>
		<Type>Hinweis</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A105*1-B" ObjectType="Connector_occurrence">
		<Code>GP3016</Code>
		<Description>Prüfung auf gleiche Kontaktgehäuse-
SNR für verschiedene OKZ einer REF</Description>
		<Text>Für den Stecker A105*1-B werden im Master 4711 für die OKZ "fd84" unterschiedliche Kontaktgehäuse verbaut (A8412, A1251)</Text>
		<ResolutionHint>Für Endpunkte mit identischer REF und Stecker-Nr. (d.h. die sich nur im OKZ
unterscheiden) muss in allen LS-Modulen eines Masters dasselbe Kontaktgehäuse verbaut werden.</ResolutionHint>
		<Type>Hinweis</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A105*1-B" ObjectType="Connector_occurrence">
		<Code>GP4330</Code>
		<Description>Massebolzen-Sachnummer in
ConnectPARTS dokumentiert</Description>
		<Text>Für den Massebolzen A105*1-B der Baureihe A177 ist in ConnectPARTS keine
Sachnummer eingetragen.</Text>
		<ResolutionHint>Sachnummer in ConnectPARTS für den entsprechenden Bolzen nachtragen (lassen,
ggfs. über Team Kontaktierungssyteme).</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="22081_1" ObjectType="Core_occurrence">
		<Code>GP4104</Code>
		<Description>Leitungen mit gleicher Kontakten unterschiedlicher Oberflächen</Description>
		<Text>An beiden Enden der Leitung 22081_1 wird der gleiche Kontakt, jedoch mit unterschiedlichen Oberflächenmaterialien eingesetzt. Aufgrund potentieller Falschkonfektionierung sollte dies nach Möglichkeit vermieden werden.</Text>
		<ResolutionHint>Die Oberflächenmaterialien der verwendeten Kontakte an der Leitung der Trennstelle stimmen nicht überein. Passende Kontakte mit gleichem Oberflächenmaterial der Leitung für die Trennstelle auswählen und in Leitungssatzzeichung, inklusive KBL
eintragen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="22081_1" ObjectType="Core_occurrence">
		<Code>GP4312</Code>
		<Description>Spannungslage der Verbindung
stimmt mit Massestelle überein</Description>
		<Text>An der Verbindung 22081_1 der Massestelle mit der REF 4711 ist keine
Spannungslage eingetragen.</Text>
		<ResolutionHint>Bitte sicherstellen, dass die Spannungslage von Massestelle und Verbindung
übereinstimmen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="FX.IR.0059" ObjectType="Fixing_occurrence">
		<Code>GP3008</Code>
		<Description>POS-Nr. angegeben</Description>
		<Text>POS-Nr. nicht angegeben.</Text>
		<ResolutionHint>Ein Teil in diesem LS Modul hat keine eingetragene POS-Nummer  für PKW.
--> POS-Nummer auswählen und in Leitungssatzzeichung, inklusive KBL eintragen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="FX.IR.0059" ObjectType="Fixing_occurrence">
		<Code>GP3009</Code>
		<Description>Teile ohne Dummy-POS-Nr.</Description>
		<Text>Das Teil mit der Dummy POS-Nr. 335 benötigt eine echte POS-Nr.</Text>
		<ResolutionHint>Ein Teil in diesem LS Modul hat noch keine echte POS-Nummer.
--> Richtige POS-Nummer beantragen und KBL korrigieren.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="N100" ObjectType="Node">
		<Code>GP3017</Code>
		<Description>Keine Bandagierungs-SNR in
Stückliste</Description>
		<Text>In der Leitungssatz-Stückliste dürfen keine Bandagierungs-Sachnummern mehr aufgeführt
werden, sondern nur noch AV-Bandagierungs-Sachnummern.</Text>
		<ResolutionHint>Bitte die Bandagierungs-SNR durch die passende AV-Bandagierungs-SNR ersetzen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A1775403906" ObjectType="Part">
		<Code>GP1011</Code>
		<Description>Firma vorhanden</Description>
		<Text>Die in der KBL angegebene Firma ACME wurde in Connect nicht gefunden.</Text>
		<ResolutionHint>Die in der KBL-Datei angegebene Firma muss muss mit dem Firmen-Namen in
Connect übereinstimmen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="Iy-0.75 RD/WH" ObjectType="Part">
		<Code>GP2000</Code>
		<Description>Leitung in ConnectPARTS
vorhanden</Description>
		<Text>Die Leitung ly-0.75 RD/WH ist in ConnectPARTS nicht angelegt.</Text>
		<ResolutionHint>Die in diesem LS Modul verwendete Leitung ist nicht angelegt.
--> Leitung anlegen lassen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="B48-2x0.5 BN+GY/YE" ObjectType="Part">
		<Code>GP3001</Code>
		<Description>Bauteil/Leitung nicht gesperrt</Description>
		<Text>Die Leitung ist in ConnectPARTS im Bereich Forschung für die Baureihe
C222 gesperrt.</Text>
		<ResolutionHint>Die betroffene Leitung in diesem LS Modul ist für die Verwendung gesperrt.
--> Verwendung beim Komponentenverantwortlichen freischalten lassen, oder entsprechende Alternative zur Verwendung suchen</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A1775408733" ObjectType="Part">
		<Code>GP1007</Code>
		<Description>Benennung von Leitungssätzen</Description>
		<Text>Benennung Leitungssatz stimmt mit SRM nicht überein.</Text>
		<ResolutionHint>Die Benennung nach SRM anpassen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A1775408733" ObjectType="Part">
		<Code>GP1008</Code>
		<Description>Baureihe vorhanden</Description>
		<Text>Die in der KBL angegeben Baureihe BR222 im Bereich A1775408733 konnte in Connect
nicht gefunden werden.</Text>
		<ResolutionHint>Die in der KBL-Datei angegebene Baureihe muss mit Connect übereinstimmen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A0005456280" ObjectType="Part">
		<Code>GP4020</Code>
		<Description>ELA passend zu Leitung</Description>
		<Text>Der Außendurchmesser der Leitung 4711 liegt außerhalb des Durchmesserbereichs des ELA 0815 von 0.5 bis
0.75 an Pin 3 der REF N2*1-B.</Text>
		<ResolutionHint>Bitte anderen Ela einsetzen, der zum Aussendurchmesser der Leitung passt.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A0185455426" ObjectType="Part">
		<Code>GP4000</Code>
		<Description>Kontakt in AV Kammer zugelassen</Description>
		<Text>Der Kontakt A0185455426 an Pin 2 ist in ConnectPARTS für die AV Kammer A34564334 nicht zugelassen.</Text>
		<ResolutionHint>Auswahl eines Kontaktes, der laut CONNECT für diesen Kammerbereich des Kontaktgehäuses eingesetzt werden darf. Ggfs. Rücksprache mit BTV des
Kontaktgehäuses.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A0185455426" ObjectType="Part">
		<Code>GP4013</Code>
		<Description>Schirme dürfen nur direkt am Gehäuse oder über einen Stützpunkt angeschlossen werden.</Description>
		<Text>Der Schirm an der Verbindung 0815 ist im Stecker X15*1-B an Pin 6 am Kontakt A0185455426 angeschlossen. Das ist nicht zulässig.</Text>
		<ResolutionHint>Bitte den Schirm nur direkt am Gehäuse oder über einen Stützpunkt anschliessen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A0285450226" ObjectType="Part">
		<Code>GP4050</Code>
		<Description>Notwendige Zusatzteile in Stückliste
enthalten</Description>
		<Text>Dieses Teil ist für das Kontaktgehäuse A02854XX als notwendiges Zusatzteil definiert, das
2 Mal verbaut ist.</Text>
		<ResolutionHint>Bitte notwendige Zusatzteile in Leitungssatz aufnehmen oder Zusteuerung als 7er-Teil
im Dialog sicherstellen.</ResolutionHint>
		<Type>Fehler</Type>
	</ValidityCheckEntry>
	<ValidityCheckEntry ID="A0029896898" ObjectType="Part">
		<Code>GP3001</Code>
